execute_program()'s return value (ERROR) is correct!
Registers are correct after execute_program() call!
